[package]
name = "double-mapped-buffer"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.29"

[target.'cfg(unix)'.dependencies]
libc = "0.2.99"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["sysinfoapi", "winbase", "handleapi", "memoryapi"] }
